baseURL = "https://coder0xe.github.io/"
languageCode = "zh-CN"
title = "coder0xe's blog"
theme = "PaperMod"

[pagination]
pagerSize = 10

[markup.highlight]
style = "dracula"
lineNos = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
description = "木叶飞舞之处，火亦生生不息"
keywords = ["BUAA", "技术博客"]
author = "sudo"
mainSections = ["posts"]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = true

[menu]
[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "分类"
url = "/categories/"
weight = 2

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 3

[[menu.main]]
name = "归档"
url = "/archives/"
weight = 4

[[menu.main]]
name = "搜索"
url = "/search/"
weight = 5

[outputs]
home = ["HTML", "JSON"]
